### ISSUE TITLE
ADL 6.0 is required, update README.md

### ISSUE THREAD

**Issue by gdevenyi** [sgminer-dev/sgminer#81]
Trying a build with 5.0 says:
adl.c: In function ‘adl_error_desc’:
adl.c:173:8: error: ‘ADL_ERR_NO_XDISPLAY’ undeclared (first use in this function)

So it looks like 6.0 is required now.

Update README.md to reflect that
